# Generated by Django 3.2.8 on 2021-10-29 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_LPB', '0007_auto_20211029_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefa',
            name='hora_criacao',
        ),
        migrations.AddField(
            model_name='tarefa',
            name='data_e_hora_criacao',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='insignia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_LPB.insignia'),
        ),
    ]
