# Generated by Django 3.2.8 on 2021-10-27 20:45

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app_LPB', '0005_alter_dadossede_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='tarefa',
            name='frequencia_semana',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('SE', 'Segunda'), ('TE', 'Terça'), ('QA', 'Quarta'), ('QI', 'Quinta'), ('SX', 'Sexta'), ('SA', 'Sabado'), ('DM', 'Domingo')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_LPB.usuario'),
        ),
    ]
