# Generated by Django 3.2.8 on 2021-10-29 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_LPB', '0008_auto_20211029_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefa',
            name='data_e_hora_criacao',
        ),
        migrations.RemoveField(
            model_name='tarefa',
            name='duracao',
        ),
    ]
