# Generated by Django 3.2.9 on 2021-11-06 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_LPB', '0010_alter_tarefa_hora_notificacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='data_e_hora_criacao',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='duracao',
            field=models.TimeField(null=True),
        ),
    ]
