# Generated by Django 3.2.9 on 2021-11-06 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_LPB', '0011_auto_20211106_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefa',
            name='data_e_hora_criacao',
        ),
        migrations.AddField(
            model_name='tarefa',
            name='data_criacao',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='hora_criacao',
            field=models.TimeField(null=True),
        ),
    ]
