# Generated by Django 3.2.9 on 2021-11-07 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_LPB', '0013_auto_20211107_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefa',
            name='ano_criacao',
        ),
        migrations.RemoveField(
            model_name='tarefa',
            name='criacao_hora',
        ),
        migrations.RemoveField(
            model_name='tarefa',
            name='criacao_minutos',
        ),
        migrations.RemoveField(
            model_name='tarefa',
            name='dia_criacao',
        ),
        migrations.RemoveField(
            model_name='tarefa',
            name='duracao_horas',
        ),
        migrations.RemoveField(
            model_name='tarefa',
            name='duracao_minutos',
        ),
        migrations.RemoveField(
            model_name='tarefa',
            name='duracao_segundos',
        ),
        migrations.RemoveField(
            model_name='tarefa',
            name='mes_criacao',
        ),
        migrations.RemoveField(
            model_name='tarefa',
            name='notificacao_hora',
        ),
        migrations.RemoveField(
            model_name='tarefa',
            name='notificacao_minutos',
        ),
        migrations.AddField(
            model_name='tarefa',
            name='data_e_hora_criacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='duracao',
            field=models.IntegerField(choices=[(1800, '0h30m'), (3600, '1h0m'), (5400, '1h30m'), (7200, '2h0m'), (9000, '2h30m'), (10800, '3h0m')], default=1800),
        ),
    ]
