# Generated by Django 3.2.9 on 2021-11-07 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_LPB', '0015_alter_tarefa_data_e_hora_criacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefa',
            name='concluida',
        ),
    ]
